import Head from 'next/head'
import Main from '../../components/readlist/Main'
import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import pageTransition from '../../utils/pageTransition'
import checkAuth from '../../utils/checkAuth'

export default function Home() {
  const [auth, setAuth] = useState(false)
  const [user, setUser] = useState(null)
  
  useEffect(() => {
    const Auth = async () => {
      try {
        const res = await checkAuth()
        setAuth(res?.auth)
        setUser(res?.user)
      } catch (error) {
        console.log(error.message)
      }
    }
    Auth()
  }, [])

  return (
    <motion.div
      variants={pageTransition}
      initial="initial"
      animate="in"
      exit="out"
      className='w-full'
    >
      <Head>
        {user && (
          <title>{user.username}/readlist</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        (auth) && (
            <Main user={user} />
        )
      }
    </motion.div>
  )
}