import axios from 'axios'
import { useRouter } from 'next/router'
import Image from 'next/image'
import Icon from '@mdi/react'
import { mdiArrowLeftCircle } from '@mdi/js'
import { motion } from 'framer-motion'
import pageTransition from '../../utils/pageTransition'
import Head from 'next/head'

const Profile = ({ user }) => {
    const router = useRouter()
    if(user) {
        return (
            <motion.div
                variants={pageTransition}
                initial="initial"
                animate="in"
                exit="out"
                className="overflow-y-scroll w-full"
            >
                <Head>
                    <title>Traversify/{user?.username}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className='p-6'>
                    <div className='flex items-center space-x-3'>
                        <div className='hover:scale-105 duration-300 ease-in-out' onClick={() => router.back(-1)}>
                            <Icon path={mdiArrowLeftCircle} size={1.3} color='gray' />
                        </div>
                        <div className='font-semibold'>Profiles/{user.username}</div>
                    </div>
                    <div className='flex flex-col space-y-4'>
                        <div className='flex items-center'>
                            <div className='w-36 h-36'>
                                <Image 
                                    src={`/assets/hp_badges/${user?.house}.png`} 
                                    height={200}
                                    width={200} 
                                    alt={user?.house} 
                                />
                            </div>
                            <div className='font-semibold'>
                                <div className='text-2xl'>{user?.firstname + " " + user?.lastname}</div>
                                <div className='text-gray-500'>{user?.username}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </motion.div>
        )
    }
}

export default Profile

export async function getServerSideProps({ params }) {
    const id = params.id
    const response = await axios.get(`http://localhost:3000/api/users/${id}`)
    return {
        props: {"user": response?.data[0]}
    }
}